### ISSUE TITLE
[TEST] - Detalles de una votacion

### ISSUE THREAD

**Issue by jvegax** [jvegax/decide-front#16]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *En progreso* | *Tests* | *joscacgom y luisUsrDev* |     *5*  |

### Descripción:
Se debe comprobar que se muestra correctamente los detalles de una votación

### Solución Adoptada:
Se han realizado los tests necesarios

### Posibles Soluciones:
- No aplica

**Comment by joscacgom** [comment]
Los tests ya estan hechos a la espera del merge con main
