### ISSUE TITLE
[Test] - Internacionalizar formularios

### ISSUE THREAD

**Issue by jvegax** [jvegax/decide-front#24]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *En progreso* | *Tests* | *LuisUsrDev, joscacgom, Jorge Toledo Vega* |     *5*  |

### Descripción:
Se debe comprobar que el sistema renderiza los diferentes formularios en los distintos idiomas disponibles: Aleman, Sueco, Inglés y Español 

- [x] Formulario de votacion y censo en Aleman
- [x] Formulario de votacion y censo en Sueco
- [x] Formulario de votacion y censo en Ingles
- [x] Formulario de votacion y censo en Español
- [x] Inicio de sesion Aleman
- [x] Inicio de sesion Sueco
- [x] Inicio de sesion Ingles
- [x] Inicio de sesion Español
- [x] Registro de usuario en Aleman
- [x] Registro de usuario en Sueco
- [x] Registro de usuario en Ingles
- [x] Registro de usuario en Español

### Solución Adoptada:
Se han realizado los tests necesarios

### Posibles Soluciones:
- No aplica

**Comment by joscacgom** [comment]
Se han realizado los tests de traducción para el componente de detalles de votación
