### ISSUE TITLE
[Test]-Cambiar estado de una votación(Botones del componente, opciones de voto etc.)

### ISSUE THREAD

**Issue by LuisUsrDev** [jvegax/decide-front#33]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *En progreso* | *Tests* | *Equipo Telegram bot* |     *5*  |

### Descripción:
Implementar un test que testee el cambio de estado de una votación. Comprobar que los botones de empezar/parar/tally cambian según el estado de la votación, las opciones de votación. Validar tanto para usuario admin como para usuario normal.

### Solución Adoptada:
Se han realizado los tests necesarios

### Posibles Soluciones:
- No aplica

**Comment by joscacgom** [comment]
La descripción ha sido levemente editada

**Comment by LuisUsrDev** [comment]
Se han implementado los test satisfactoriamente.
