### ISSUE TITLE
INC-010

### ISSUE THREAD

**Issue by josmarlop16** [jvegax/decide-front#34]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *Cerrado* | *Funcionalidad* | *josmarlop16* |     *5*  |

### Descripción:
Se pide que cualquier usuario pueda registrarse en decide, iniciar sesion y cerrar sesion cuando le plazca

### Solución Adoptada:
Se han añadido las funcionalidades descritas

### Posibles Soluciones:
- No aplica

**Comment by josmarlop16** [comment]
Se han realizado las funcionalidades descritas tal y como se pedian

**Comment by joscacgom** [comment]
La incidencia ha sido renombrada con INC-017 en vez de como estaba antes INC-010 puesto que la INC-010 ya estaba descrita y no se pueden repetir dicho código de identificación.
